export let mockChart = [
    [
        { value: '', color: '#fff' },
        { value: '10:00', color: '#fff' },
        { value: '10:15', color: '#fff' },
        { value: '10:30', color: '#fff' },
        { value: '10:45', color: '#fff' },
        { value: '11:00', color: '#fff' },
        { value: '11:00', color: '#fff' },
        { value: '11:15', color: '#fff' },
        { value: '11:30', color: '#fff' },
        { value: '11:45', color: '#fff' },
        { value: '12:00', color: '#fff' },
        { value: '12:00', color: '#fff' },
        { value: '12:15', color: '#fff' },
        { value: '12:30', color: '#fff' },
        { value: '12:45', color: '#fff' },
        { value: '13:00', color: '#fff' },
        { value: '13:15', color: '#fff' },
        { value: '13:30', color: '#fff' },
        { value: '13:45', color: '#fff' },
        { value: '14:00', color: '#fff' },
        { value: '15:15', color: '#fff' },
        { value: '15:30', color: '#fff' },
        { value: '15:45', color: '#fff' },
        { value: '16:00', color: '#fff' },
        { value: '16:15', color: '#fff' },
        { value: '16:30', color: '#fff' },
        { value: '16:45', color: '#fff' },
        { value: '17:00', color: '#fff' },
        { value: '17:15', color: '#fff' },
        { value: '17:30', color: '#fff' },
        { value: '17:45', color: '#fff' },
        { value: '18:00', color: '#fff' },
    ],
    [
        { value: 'Вася', color: '#fff', colspan: 1 },
        { value: '', color: '#fff', colspan: 5 },
        { value: 'Сейчас обедает Вася', color: '#81C784', colspan: 4 },
        { value: '', color: '#fff', colspan: 22 },
    ],
    [
        { value: 'Иван', color: '#fff', colspan: 1 },
        { value: '', color: '#fff', colspan: 1 },
        { value: 'Сейчас обедает Иван', color: '#81C784', colspan: 5 },
        { value: '', color: '#fff', colspan: 25 },
    ],
    [
        { value: 'Лиза', color: '#fff', colspan: 1 },
        { value: '', color: '#fff', colspan: 14 },
        { value: 'Сейчас обедает Лиза', color: '#81C784', colspan: 3 },
        { value: '', color: '#fff', colspan: 14 },
    ],
    [
        { value: 'Саша', color: '#fff', colspan: 1 },
        { value: '', color: '#fff', colspan: 23 },
        { value: 'Сейчас обедает Саша', color: '#81C784', colspan: 5 },
        { value: '', color: '#fff', colspan: 4 },
    ],
]